### ISSUE TITLE
format error in schedule.yaml, help pls.

### ISSUE THREAD

**Issue by dianaiusan** [coderefinery/2025-03-25-workshop#1]
Could I get help with https://github.com/coderefinery/2025-03-25-workshop/blob/main/content/schedule.yaml?

I am trying to have a shell crash course and help session on March 19 and one install on March 24, but I think I have a format error somewhere in the yaml file.

**Comment by bast** [comment]
I use https://github.com/adrienverge/yamllint to check yaml files. I will do that in a moment.

**Comment by bast** [comment]
```
$ yamllint schedule.yaml

schedule.yaml
  14:5      error    duplication of key "date" in mapping  (key-duplicates)
  15:5      error    duplication of key "sessions" in mapping  (key-duplicates)
```

This means there is a `- title` line missing in front of the second `date:` in:
```yaml
  - title: "Shell crash course and installation help"
    date: "2025-03-19"
    sessions:
      - starts: 12:00
        ends: 12:30
        title: Shell crash course (optional)
      - starts: 12:30
        ends: 13:30
        title: Installation help for everybody (option 1)
        url: https://coderefinery.github.io/installation/
    date: "2025-03-24"
    sessions:
      - starts: 12:30
        ends: 14:00
        title: Installation help for everybody (option 2)
        url: https://coderefinery.github.io/installation/
```
